import '../styles/globals.css'
import Head from 'next/head'
import {MoralisProvider} from "react-moralis";

function MyApp({ Component, pageProps }) {

  return <MoralisProvider 
            appId="2usVTlONkHgHkToWJNY6WEaWsklpD2PD5bjkhZ8T" 
            serverUrl="https://shwkwtgzxazu.usemoralis.com:2053/server">

            <Head>
              <title>Create Next App</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            <Component {...pageProps} />
          </MoralisProvider>
}

export default MyApp
